/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace netspire {

public enum AnnouncementState {
  PENDING = 0,
  WAITING_TO_ANNOUNCE,
  ACTIVE,
  COMPLETED,
  CANCELLED,
  WAITING_TO_STOP,
  INTERRUPTED,
  FAILED,
  PENDING_FILE_CREATE,
  WAITING_PLAYER,
  SYNC_COMPLETE,
  PENDING_FILE_TRANSFER
}

}
