/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace netspire {

public enum AnnouncementType {
  AT_LIVE = 0,
  AT_STORED_DATA,
  AT_DVA,
  AT_DISPLAY_v0,
  AT_TTS,
  AT_BGM,
  AT_MIXED,
  AT_NONE,
  AT_TEMPLATE,
  AT_DISPLAY_TEMPLATE,
  AT_TTS_SAF,
  AT_STORED_DATA_SAF,
  AT_MAX_ANNOUNCEMENT_TYPES
}

}
