/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace netspire {

using System;
using System.Runtime.InteropServices;

public class PaSWTrigger : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PaSWTrigger(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PaSWTrigger obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PaSWTrigger() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          netspireSDKPINVOKE.delete_PaSWTrigger(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public PaTrigger trigger {
    set {
      netspireSDKPINVOKE.PaSWTrigger_trigger_set(swigCPtr, PaTrigger.getCPtr(value));
    } 
    get {
      IntPtr cPtr = netspireSDKPINVOKE.PaSWTrigger_trigger_get(swigCPtr);
      PaTrigger ret = (cPtr == IntPtr.Zero) ? null : new PaTrigger(cPtr, false);
      return ret;
    } 
  }

  public int associatedSourceId {
    set {
      netspireSDKPINVOKE.PaSWTrigger_associatedSourceId_set(swigCPtr, value);
    } 
    get {
      int ret = netspireSDKPINVOKE.PaSWTrigger_associatedSourceId_get(swigCPtr);
      return ret;
    } 
  }

  public PaSWTrigger() : this(netspireSDKPINVOKE.new_PaSWTrigger(), true) {
  }

}

}
