/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace netspire {

using System;
using System.Runtime.InteropServices;

public class ServiceStop : TripStop {
  private HandleRef swigCPtr;

  internal ServiceStop(IntPtr cPtr, bool cMemoryOwn) : base(netspireSDKPINVOKE.ServiceStop_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ServiceStop obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ServiceStop() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          netspireSDKPINVOKE.delete_ServiceStop(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public ServiceStop() : this(netspireSDKPINVOKE.new_ServiceStop__SWIG_0(), true) {
  }

  public ServiceStop(int id) : this(netspireSDKPINVOKE.new_ServiceStop__SWIG_1(id), true) {
  }

  public void setServiceId(int serviceId) {
    netspireSDKPINVOKE.ServiceStop_setServiceId(swigCPtr, serviceId);
  }

  public int getServiceId() {
    int ret = netspireSDKPINVOKE.ServiceStop_getServiceId(swigCPtr);
    return ret;
  }

  public void setTripStopId(int tripStopId) {
    netspireSDKPINVOKE.ServiceStop_setTripStopId(swigCPtr, tripStopId);
  }

  public int getTripStopId() {
    int ret = netspireSDKPINVOKE.ServiceStop_getTripStopId(swigCPtr);
    return ret;
  }

  public void setServiceStartTime(uint serviceStartTime) {
    netspireSDKPINVOKE.ServiceStop_setServiceStartTime(swigCPtr, serviceStartTime);
  }

  public uint getServiceStartTime() {
    uint ret = netspireSDKPINVOKE.ServiceStop_getServiceStartTime(swigCPtr);
    return ret;
  }

  public void setArvDelay(uint arvDelay) {
    netspireSDKPINVOKE.ServiceStop_setArvDelay(swigCPtr, arvDelay);
  }

  public uint getArvDelay() {
    uint ret = netspireSDKPINVOKE.ServiceStop_getArvDelay(swigCPtr);
    return ret;
  }

  public void setDepDelay(uint depDelay) {
    netspireSDKPINVOKE.ServiceStop_setDepDelay(swigCPtr, depDelay);
  }

  public uint getDepDelay() {
    uint ret = netspireSDKPINVOKE.ServiceStop_getDepDelay(swigCPtr);
    return ret;
  }

  public void setArvTime(uint arvTime) {
    netspireSDKPINVOKE.ServiceStop_setArvTime(swigCPtr, arvTime);
  }

  public uint getArvTime() {
    uint ret = netspireSDKPINVOKE.ServiceStop_getArvTime(swigCPtr);
    return ret;
  }

  public void setDepTime(uint depTime) {
    netspireSDKPINVOKE.ServiceStop_setDepTime(swigCPtr, depTime);
  }

  public uint getDepTime() {
    uint ret = netspireSDKPINVOKE.ServiceStop_getDepTime(swigCPtr);
    return ret;
  }

  public void setDelay(uint delay) {
    netspireSDKPINVOKE.ServiceStop_setDelay(swigCPtr, delay);
  }

}

}
