/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace netspire {

using System;
using System.Runtime.InteropServices;

public class DISPLAY_VALUE_INFO : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DISPLAY_VALUE_INFO(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DISPLAY_VALUE_INFO obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DISPLAY_VALUE_INFO() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          netspireSDKPINVOKE.delete_DISPLAY_VALUE_INFO(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string text {
    set {
      netspireSDKPINVOKE.DISPLAY_VALUE_INFO_text_set(swigCPtr, value);
      if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = netspireSDKPINVOKE.DISPLAY_VALUE_INFO_text_get(swigCPtr);
      if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int timeout {
    set {
      netspireSDKPINVOKE.DISPLAY_VALUE_INFO_timeout_set(swigCPtr, value);
    } 
    get {
      int ret = netspireSDKPINVOKE.DISPLAY_VALUE_INFO_timeout_get(swigCPtr);
      return ret;
    } 
  }

  public DISPLAY_VALUE_INFO() : this(netspireSDKPINVOKE.new_DISPLAY_VALUE_INFO__SWIG_0(), true) {
  }

  public DISPLAY_VALUE_INFO(string _text, int _timeout) : this(netspireSDKPINVOKE.new_DISPLAY_VALUE_INFO__SWIG_1(_text, _timeout), true) {
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
