/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace netspire {

using System;
using System.Runtime.InteropServices;

public class netspireSDK {
  public static int gMaxServerWaitTimeSeconds {
    set {
      netspireSDKPINVOKE.gMaxServerWaitTimeSeconds_set(value);
    } 
    get {
      int ret = netspireSDKPINVOKE.gMaxServerWaitTimeSeconds_get();
      return ret;
    } 
  }

  public static string stateName(int id) {
    string ret = netspireSDKPINVOKE.stateName(id);
    return ret;
  }

  public static string typeName(int id) {
    string ret = netspireSDKPINVOKE.typeName(id);
    return ret;
  }

  public static string trunkStatusName(int id, TRUNK_TYPE type) {
    string ret = netspireSDKPINVOKE.trunkStatusName(id, (int)type);
    return ret;
  }

  public static string getCodecString(CODEC codecId) {
    string ret = netspireSDKPINVOKE.getCodecString((int)codecId);
    return ret;
  }

  public static CODEC getCodecId(string codecString) {
    CODEC ret = (CODEC)netspireSDKPINVOKE.getCodecId(codecString);
    return ret;
  }

  public static readonly int MINIMUM_PRIORITY_LEVEL = netspireSDKPINVOKE.MINIMUM_PRIORITY_LEVEL_get();
  public static readonly int MAXIMUM_PRIORITY_LEVEL = netspireSDKPINVOKE.MAXIMUM_PRIORITY_LEVEL_get();
  public static readonly int DEFAULT_PRIORITY_LEVEL = netspireSDKPINVOKE.DEFAULT_PRIORITY_LEVEL_get();
  public static readonly int DEFAULT_RELATIVE_PRIORITY_LOW = netspireSDKPINVOKE.DEFAULT_RELATIVE_PRIORITY_LOW_get();
  public static readonly int DEFAULT_RELATIVE_PRIORITY_NORMAL = netspireSDKPINVOKE.DEFAULT_RELATIVE_PRIORITY_NORMAL_get();
  public static readonly int DEFAULT_RELATIVE_PRIORITY_HIGH = netspireSDKPINVOKE.DEFAULT_RELATIVE_PRIORITY_HIGH_get();
  public static readonly int DEFAULT_RELATIVE_PRIORITY_EMERGENCY = netspireSDKPINVOKE.DEFAULT_RELATIVE_PRIORITY_EMERGENCY_get();
}

}
