/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace netspire {

public enum TRUNK_STATUS {
  TRUNK_STATUS_NONE = 0,
  TRUNK_STATUS_UP,
  TRUNK_STATUS_DOWN,
  TRUNK_STATUS_FAIL
}

}
