/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace netspire {

using System;
using System.Runtime.InteropServices;

public class AlarmArray : IDisposable, System.Collections.IEnumerable
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IEnumerable<Alarm>
#endif
 {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AlarmArray(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(AlarmArray obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~AlarmArray() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          netspireSDKPINVOKE.delete_AlarmArray(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public AlarmArray(System.Collections.ICollection c) : this() {
    if (c == null)
      throw new ArgumentNullException("c");
    foreach (Alarm element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Alarm this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array)
#else
  public void CopyTo(Alarm[] array)
#endif
  {
    CopyTo(0, array, 0, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array, int arrayIndex)
#else
  public void CopyTo(Alarm[] array, int arrayIndex)
#endif
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(int index, System.Array array, int arrayIndex, int count)
#else
  public void CopyTo(int index, Alarm[] array, int arrayIndex, int count)
#endif
  {
    if (array == null)
      throw new ArgumentNullException("array");
    if (index < 0)
      throw new ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

#if !SWIG_DOTNET_1
  System.Collections.Generic.IEnumerator<Alarm> System.Collections.Generic.IEnumerable<Alarm>.GetEnumerator() {
    return new AlarmArrayEnumerator(this);
  }
#endif

  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return new AlarmArrayEnumerator(this);
  }

  public AlarmArrayEnumerator GetEnumerator() {
    return new AlarmArrayEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class AlarmArrayEnumerator : System.Collections.IEnumerator
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IEnumerator<Alarm>
#endif
  {
    private AlarmArray collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public AlarmArrayEnumerator(AlarmArray collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Alarm Current {
      get {
        if (currentIndex == -1)
          throw new InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new InvalidOperationException("Collection modified.");
        return (Alarm)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new InvalidOperationException("Collection modified.");
      }
    }

#if !SWIG_DOTNET_1
    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
#endif
  }

  public void Clear() {
    netspireSDKPINVOKE.AlarmArray_Clear(swigCPtr);
  }

  public void Add(Alarm x) {
    netspireSDKPINVOKE.AlarmArray_Add(swigCPtr, Alarm.getCPtr(x));
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = netspireSDKPINVOKE.AlarmArray_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = netspireSDKPINVOKE.AlarmArray_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    netspireSDKPINVOKE.AlarmArray_reserve(swigCPtr, n);
  }

  public AlarmArray() : this(netspireSDKPINVOKE.new_AlarmArray__SWIG_0(), true) {
  }

  public AlarmArray(AlarmArray other) : this(netspireSDKPINVOKE.new_AlarmArray__SWIG_1(AlarmArray.getCPtr(other)), true) {
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public AlarmArray(int capacity) : this(netspireSDKPINVOKE.new_AlarmArray__SWIG_2(capacity), true) {
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  private Alarm getitemcopy(int index) {
    Alarm ret = new Alarm(netspireSDKPINVOKE.AlarmArray_getitemcopy(swigCPtr, index), true);
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private Alarm getitem(int index) {
    Alarm ret = new Alarm(netspireSDKPINVOKE.AlarmArray_getitem(swigCPtr, index), false);
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Alarm val) {
    netspireSDKPINVOKE.AlarmArray_setitem(swigCPtr, index, Alarm.getCPtr(val));
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(AlarmArray values) {
    netspireSDKPINVOKE.AlarmArray_AddRange(swigCPtr, AlarmArray.getCPtr(values));
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public AlarmArray GetRange(int index, int count) {
    IntPtr cPtr = netspireSDKPINVOKE.AlarmArray_GetRange(swigCPtr, index, count);
    AlarmArray ret = (cPtr == IntPtr.Zero) ? null : new AlarmArray(cPtr, true);
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Alarm x) {
    netspireSDKPINVOKE.AlarmArray_Insert(swigCPtr, index, Alarm.getCPtr(x));
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, AlarmArray values) {
    netspireSDKPINVOKE.AlarmArray_InsertRange(swigCPtr, index, AlarmArray.getCPtr(values));
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    netspireSDKPINVOKE.AlarmArray_RemoveAt(swigCPtr, index);
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    netspireSDKPINVOKE.AlarmArray_RemoveRange(swigCPtr, index, count);
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public static AlarmArray Repeat(Alarm value, int count) {
    IntPtr cPtr = netspireSDKPINVOKE.AlarmArray_Repeat(Alarm.getCPtr(value), count);
    AlarmArray ret = (cPtr == IntPtr.Zero) ? null : new AlarmArray(cPtr, true);
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    netspireSDKPINVOKE.AlarmArray_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    netspireSDKPINVOKE.AlarmArray_Reverse__SWIG_1(swigCPtr, index, count);
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, AlarmArray values) {
    netspireSDKPINVOKE.AlarmArray_SetRange(swigCPtr, index, AlarmArray.getCPtr(values));
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
