/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace netspire {

using System;
using System.Runtime.InteropServices;

public class CDRInfo : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CDRInfo(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CDRInfo obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CDRInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          netspireSDKPINVOKE.delete_CDRInfo(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public CDRInfo() : this(netspireSDKPINVOKE.new_CDRInfo__SWIG_0(), true) {
  }

  public CDRInfo(CDRInfo cdrInfoAnother) : this(netspireSDKPINVOKE.new_CDRInfo__SWIG_1(CDRInfo.getCPtr(cdrInfoAnother)), true) {
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public int id {
    set {
      netspireSDKPINVOKE.CDRInfo_id_set(swigCPtr, value);
    } 
    get {
      int ret = netspireSDKPINVOKE.CDRInfo_id_get(swigCPtr);
      return ret;
    } 
  }

  public int startDateYear {
    set {
      netspireSDKPINVOKE.CDRInfo_startDateYear_set(swigCPtr, value);
    } 
    get {
      int ret = netspireSDKPINVOKE.CDRInfo_startDateYear_get(swigCPtr);
      return ret;
    } 
  }

  public int startDateMonth {
    set {
      netspireSDKPINVOKE.CDRInfo_startDateMonth_set(swigCPtr, value);
    } 
    get {
      int ret = netspireSDKPINVOKE.CDRInfo_startDateMonth_get(swigCPtr);
      return ret;
    } 
  }

  public int startDateDay {
    set {
      netspireSDKPINVOKE.CDRInfo_startDateDay_set(swigCPtr, value);
    } 
    get {
      int ret = netspireSDKPINVOKE.CDRInfo_startDateDay_get(swigCPtr);
      return ret;
    } 
  }

  public int startTimeHour {
    set {
      netspireSDKPINVOKE.CDRInfo_startTimeHour_set(swigCPtr, value);
    } 
    get {
      int ret = netspireSDKPINVOKE.CDRInfo_startTimeHour_get(swigCPtr);
      return ret;
    } 
  }

  public int startTimeMinute {
    set {
      netspireSDKPINVOKE.CDRInfo_startTimeMinute_set(swigCPtr, value);
    } 
    get {
      int ret = netspireSDKPINVOKE.CDRInfo_startTimeMinute_get(swigCPtr);
      return ret;
    } 
  }

  public int startTimeSecond {
    set {
      netspireSDKPINVOKE.CDRInfo_startTimeSecond_set(swigCPtr, value);
    } 
    get {
      int ret = netspireSDKPINVOKE.CDRInfo_startTimeSecond_get(swigCPtr);
      return ret;
    } 
  }

  public int callDuration {
    set {
      netspireSDKPINVOKE.CDRInfo_callDuration_set(swigCPtr, value);
    } 
    get {
      int ret = netspireSDKPINVOKE.CDRInfo_callDuration_get(swigCPtr);
      return ret;
    } 
  }

  public int answerDuration {
    set {
      netspireSDKPINVOKE.CDRInfo_answerDuration_set(swigCPtr, value);
    } 
    get {
      int ret = netspireSDKPINVOKE.CDRInfo_answerDuration_get(swigCPtr);
      return ret;
    } 
  }

  public string callFromTermId {
    set {
      netspireSDKPINVOKE.CDRInfo_callFromTermId_set(swigCPtr, value);
      if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = netspireSDKPINVOKE.CDRInfo_callFromTermId_get(swigCPtr);
      if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string callToTermIdList {
    set {
      netspireSDKPINVOKE.CDRInfo_callToTermIdList_set(swigCPtr, value);
      if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = netspireSDKPINVOKE.CDRInfo_callToTermIdList_get(swigCPtr);
      if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int callCompletionStatus {
    set {
      netspireSDKPINVOKE.CDRInfo_callCompletionStatus_set(swigCPtr, value);
    } 
    get {
      int ret = netspireSDKPINVOKE.CDRInfo_callCompletionStatus_get(swigCPtr);
      return ret;
    } 
  }

}

}
