/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace netspire {

using System;
using System.Runtime.InteropServices;

public class IntValueMap : IDisposable 
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IDictionary<int, int>
#endif
 {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IntValueMap(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(IntValueMap obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~IntValueMap() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          netspireSDKPINVOKE.delete_IntValueMap(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }


  public int this[int key] {
    get {
      return getitem(key);
    }

    set {
      setitem(key, value);
    }
  }

  public bool TryGetValue(int key, out int value) {
    if (this.ContainsKey(key)) {
      value = this[key];
      return true;
    }
    value = default(int);
    return false;
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsReadOnly {
    get { 
      return false; 
    }
  }

#if !SWIG_DOTNET_1

  public System.Collections.Generic.ICollection<int> Keys {
    get {
      System.Collections.Generic.ICollection<int> keys = new System.Collections.Generic.List<int>();
      int size = this.Count;
      if (size > 0) {
        IntPtr iter = create_iterator_begin();
        for (int i = 0; i < size; i++) {
          keys.Add(get_next_key(iter));
        }
        destroy_iterator(iter);
      }
      return keys;
    }
  }

  public System.Collections.Generic.ICollection<int> Values {
    get {
      System.Collections.Generic.ICollection<int> vals = new System.Collections.Generic.List<int>();
      foreach (System.Collections.Generic.KeyValuePair<int, int> pair in this) {
        vals.Add(pair.Value);
      }
      return vals;
    }
  }
  
  public void Add(System.Collections.Generic.KeyValuePair<int, int> item) {
    Add(item.Key, item.Value);
  }

  public bool Remove(System.Collections.Generic.KeyValuePair<int, int> item) {
    if (Contains(item)) {
      return Remove(item.Key);
    } else {
      return false;
    }
  }

  public bool Contains(System.Collections.Generic.KeyValuePair<int, int> item) {
    if (this[item.Key] == item.Value) {
      return true;
    } else {
      return false;
    }
  }

  public void CopyTo(System.Collections.Generic.KeyValuePair<int, int>[] array) {
    CopyTo(array, 0);
  }

  public void CopyTo(System.Collections.Generic.KeyValuePair<int, int>[] array, int arrayIndex) {
    if (array == null)
      throw new ArgumentNullException("array");
    if (arrayIndex < 0)
      throw new ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (array.Rank > 1)
      throw new ArgumentException("Multi dimensional array.", "array");
    if (arrayIndex+this.Count > array.Length)
      throw new ArgumentException("Number of elements to copy is too large.");

    System.Collections.Generic.IList<int> keyList = new System.Collections.Generic.List<int>(this.Keys);
    for (int i = 0; i < keyList.Count; i++) {
      int currentKey = keyList[i];
      array.SetValue(new System.Collections.Generic.KeyValuePair<int, int>(currentKey, this[currentKey]), arrayIndex+i);
    }
  }

  System.Collections.Generic.IEnumerator<System.Collections.Generic.KeyValuePair<int, int>> System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<int, int>>.GetEnumerator() {
    return new IntValueMapEnumerator(this);
  }

  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return new IntValueMapEnumerator(this);
  }

  public IntValueMapEnumerator GetEnumerator() {
    return new IntValueMapEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class IntValueMapEnumerator : System.Collections.IEnumerator, 
      System.Collections.Generic.IEnumerator<System.Collections.Generic.KeyValuePair<int, int>>
  {
    private IntValueMap collectionRef;
    private System.Collections.Generic.IList<int> keyCollection;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public IntValueMapEnumerator(IntValueMap collection) {
      collectionRef = collection;
      keyCollection = new System.Collections.Generic.List<int>(collection.Keys);
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public System.Collections.Generic.KeyValuePair<int, int> Current {
      get {
        if (currentIndex == -1)
          throw new InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new InvalidOperationException("Collection modified.");
        return (System.Collections.Generic.KeyValuePair<int, int>)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        int currentKey = keyCollection[currentIndex];
        currentObject = new System.Collections.Generic.KeyValuePair<int, int>(currentKey, collectionRef[currentKey]);
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
      currentIndex = -1;
      currentObject = null;
    }
  }
#endif
  

  public IntValueMap() : this(netspireSDKPINVOKE.new_IntValueMap__SWIG_0(), true) {
  }

  public IntValueMap(IntValueMap other) : this(netspireSDKPINVOKE.new_IntValueMap__SWIG_1(IntValueMap.getCPtr(other)), true) {
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = netspireSDKPINVOKE.IntValueMap_size(swigCPtr);
    return ret;
  }

  public bool empty() {
    bool ret = netspireSDKPINVOKE.IntValueMap_empty(swigCPtr);
    return ret;
  }

  public void Clear() {
    netspireSDKPINVOKE.IntValueMap_Clear(swigCPtr);
  }

  private int getitem(int key) {
    int ret = netspireSDKPINVOKE.IntValueMap_getitem(swigCPtr, key);
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int key, int x) {
    netspireSDKPINVOKE.IntValueMap_setitem(swigCPtr, key, x);
  }

  public bool ContainsKey(int key) {
    bool ret = netspireSDKPINVOKE.IntValueMap_ContainsKey(swigCPtr, key);
    return ret;
  }

  public void Add(int key, int val) {
    netspireSDKPINVOKE.IntValueMap_Add(swigCPtr, key, val);
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Remove(int key) {
    bool ret = netspireSDKPINVOKE.IntValueMap_Remove(swigCPtr, key);
    return ret;
  }

  private IntPtr create_iterator_begin() {
    IntPtr ret = netspireSDKPINVOKE.IntValueMap_create_iterator_begin(swigCPtr);
    return ret;
  }

  private int get_next_key(IntPtr swigiterator) {
    int ret = netspireSDKPINVOKE.IntValueMap_get_next_key(swigCPtr, swigiterator);
    return ret;
  }

  private void destroy_iterator(IntPtr swigiterator) {
    netspireSDKPINVOKE.IntValueMap_destroy_iterator(swigCPtr, swigiterator);
  }

}

}
