/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace netspire {

using System;
using System.Runtime.InteropServices;

public class SIPTrunkList : IDisposable, System.Collections.IEnumerable
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IEnumerable<SIPTrunk>
#endif
 {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SIPTrunkList(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(SIPTrunkList obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~SIPTrunkList() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          netspireSDKPINVOKE.delete_SIPTrunkList(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public SIPTrunkList(System.Collections.ICollection c) : this() {
    if (c == null)
      throw new ArgumentNullException("c");
    foreach (SIPTrunk element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public SIPTrunk this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array)
#else
  public void CopyTo(SIPTrunk[] array)
#endif
  {
    CopyTo(0, array, 0, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array, int arrayIndex)
#else
  public void CopyTo(SIPTrunk[] array, int arrayIndex)
#endif
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(int index, System.Array array, int arrayIndex, int count)
#else
  public void CopyTo(int index, SIPTrunk[] array, int arrayIndex, int count)
#endif
  {
    if (array == null)
      throw new ArgumentNullException("array");
    if (index < 0)
      throw new ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

#if !SWIG_DOTNET_1
  System.Collections.Generic.IEnumerator<SIPTrunk> System.Collections.Generic.IEnumerable<SIPTrunk>.GetEnumerator() {
    return new SIPTrunkListEnumerator(this);
  }
#endif

  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return new SIPTrunkListEnumerator(this);
  }

  public SIPTrunkListEnumerator GetEnumerator() {
    return new SIPTrunkListEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class SIPTrunkListEnumerator : System.Collections.IEnumerator
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IEnumerator<SIPTrunk>
#endif
  {
    private SIPTrunkList collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public SIPTrunkListEnumerator(SIPTrunkList collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public SIPTrunk Current {
      get {
        if (currentIndex == -1)
          throw new InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new InvalidOperationException("Collection modified.");
        return (SIPTrunk)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new InvalidOperationException("Collection modified.");
      }
    }

#if !SWIG_DOTNET_1
    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
#endif
  }

  public void Clear() {
    netspireSDKPINVOKE.SIPTrunkList_Clear(swigCPtr);
  }

  public void Add(SIPTrunk x) {
    netspireSDKPINVOKE.SIPTrunkList_Add(swigCPtr, SIPTrunk.getCPtr(x));
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = netspireSDKPINVOKE.SIPTrunkList_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = netspireSDKPINVOKE.SIPTrunkList_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    netspireSDKPINVOKE.SIPTrunkList_reserve(swigCPtr, n);
  }

  public SIPTrunkList() : this(netspireSDKPINVOKE.new_SIPTrunkList__SWIG_0(), true) {
  }

  public SIPTrunkList(SIPTrunkList other) : this(netspireSDKPINVOKE.new_SIPTrunkList__SWIG_1(SIPTrunkList.getCPtr(other)), true) {
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public SIPTrunkList(int capacity) : this(netspireSDKPINVOKE.new_SIPTrunkList__SWIG_2(capacity), true) {
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  private SIPTrunk getitemcopy(int index) {
    SIPTrunk ret = new SIPTrunk(netspireSDKPINVOKE.SIPTrunkList_getitemcopy(swigCPtr, index), true);
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private SIPTrunk getitem(int index) {
    SIPTrunk ret = new SIPTrunk(netspireSDKPINVOKE.SIPTrunkList_getitem(swigCPtr, index), false);
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, SIPTrunk val) {
    netspireSDKPINVOKE.SIPTrunkList_setitem(swigCPtr, index, SIPTrunk.getCPtr(val));
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(SIPTrunkList values) {
    netspireSDKPINVOKE.SIPTrunkList_AddRange(swigCPtr, SIPTrunkList.getCPtr(values));
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public SIPTrunkList GetRange(int index, int count) {
    IntPtr cPtr = netspireSDKPINVOKE.SIPTrunkList_GetRange(swigCPtr, index, count);
    SIPTrunkList ret = (cPtr == IntPtr.Zero) ? null : new SIPTrunkList(cPtr, true);
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, SIPTrunk x) {
    netspireSDKPINVOKE.SIPTrunkList_Insert(swigCPtr, index, SIPTrunk.getCPtr(x));
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, SIPTrunkList values) {
    netspireSDKPINVOKE.SIPTrunkList_InsertRange(swigCPtr, index, SIPTrunkList.getCPtr(values));
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    netspireSDKPINVOKE.SIPTrunkList_RemoveAt(swigCPtr, index);
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    netspireSDKPINVOKE.SIPTrunkList_RemoveRange(swigCPtr, index, count);
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public static SIPTrunkList Repeat(SIPTrunk value, int count) {
    IntPtr cPtr = netspireSDKPINVOKE.SIPTrunkList_Repeat(SIPTrunk.getCPtr(value), count);
    SIPTrunkList ret = (cPtr == IntPtr.Zero) ? null : new SIPTrunkList(cPtr, true);
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    netspireSDKPINVOKE.SIPTrunkList_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    netspireSDKPINVOKE.SIPTrunkList_Reverse__SWIG_1(swigCPtr, index, count);
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, SIPTrunkList values) {
    netspireSDKPINVOKE.SIPTrunkList_SetRange(swigCPtr, index, SIPTrunkList.getCPtr(values));
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
