/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace netspire {

public enum ZoneHealthStatus {
  ZH_UNKNOWN = 0,
  ZH_HEALTHY,
  ZH_FAULTY,
  ZH_PARTIAL_HEALTHY
}

}
