/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace netspire {

public enum CALLTYPE {
  PEI = 0,
  ICOM,
  PA,
  TR,
  TR_PA,
  TR_EMERGENCY,
  BGM,
  PEI_EDR,
  APP,
  CP2TR,
  CT_UNKNOWN,
  CT_PEI_TYPE1 = PEI,
  CT_PEI_TYPE2 = PEI_EDR,
  PA_TYPE1 = 11
}

}
