/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace netspire {

using System;
using System.Runtime.InteropServices;

public class MessagePriority : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MessagePriority(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(MessagePriority obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~MessagePriority() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          netspireSDKPINVOKE.delete_MessagePriority(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public MessagePriority() : this(netspireSDKPINVOKE.new_MessagePriority__SWIG_0(), true) {
  }

  public MessagePriority(MessagePriority messagePriorityAnother) : this(netspireSDKPINVOKE.new_MessagePriority__SWIG_1(MessagePriority.getCPtr(messagePriorityAnother)), true) {
    if (netspireSDKPINVOKE.SWIGPendingException.Pending) throw netspireSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public MessagePriority(AnnouncementPriorityMode mode, int level) : this(netspireSDKPINVOKE.new_MessagePriority__SWIG_2((int)mode, level), true) {
  }

  public void setPriorityMode(AnnouncementPriorityMode mode) {
    netspireSDKPINVOKE.MessagePriority_setPriorityMode(swigCPtr, (int)mode);
  }

  public AnnouncementPriorityMode getPriorityMode() {
    AnnouncementPriorityMode ret = (AnnouncementPriorityMode)netspireSDKPINVOKE.MessagePriority_getPriorityMode(swigCPtr);
    return ret;
  }

  public void setPrioritylevel(int level) {
    netspireSDKPINVOKE.MessagePriority_setPrioritylevel(swigCPtr, level);
  }

  public int getPriorityLevel() {
    int ret = netspireSDKPINVOKE.MessagePriority_getPriorityLevel(swigCPtr);
    return ret;
  }

}

}
