/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace netspire {

public enum CODEC {
  CODEC_L16_48K = 0,
  CODEC_L16_16K,
  CODEC_PCMA_8K,
  CODEC_PCMU_8K,
  CODEC_CELT,
  CODEC_UNKNOWN
}

}
